baseURL = 'https://ballison.github.io/personalsite/'
languageCode = 'en-gb'
title = 'My New Hugo Site'
theme = 'hugo-blog-awesome'

[[params.socialIcons]]
name = "Rss"
url = "/index.xml"

[caches]
    [caches.images]
        dir = ':cacheDir/images'